#/bin/bash
nombreArchivo=Interoperabilidad
## --use-part-section
rst2xetex --template=latex2e/xelatex.tex --documentclass=article --documentoptions=letterpaper,11pt --use-latex-docinfo --section-subtitles --smart-quotes=yes -g -l es $nombreArchivo.rst $nombreArchivo.tex
sed -i '/^Generated by \\href{/d' $nombreArchivo.tex
#sed -i 's/\\begin{quote}/\\begin{quotation}/g' $nombreArchivo.tex
#sed -i 's/\\end{quote}/\\end{quotation}/g' $nombreArchivo.tex

latexmk -xelatex $nombreArchivo.tex



